name: trabalho2
on:
 workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v2
      with:
        login-server: aulacontainer.azurecr.io
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . -t aulacontainer.azurecr.io/k8sdemo:${{ github.sha }}
        docker push aulacontainer.azurecr.io/k8sdemo:${{ github.sha }
